### ISSUE TITLE
Wrong id in plugins.json asset for release 1.13.0

### ISSUE THREAD

**Issue by DropSnorz** [studiorack/iem-plugin-suite#1]
Hi,

It seems there is a small typo issue on the studiorack metadata file 🙂 

On the [Release 1.13.0](https://github.com/studiorack/iem-plugin-suite/releases/tag/v1.13.0), the `id` field definied in [plugins.json](https://github.com/studiorack/iem-plugin-suite/releases/download/v1.13.0/plugins.json) is set to `iem-plugin-suite.jpg` but I think it should be `iem-plugin-suite`

**Comment by kmturley** [comment]
Great find, probably a copy/paste mistake.

Updated the release:
https://github.com/studiorack/iem-plugin-suite/releases/download/v1.13.0/plugins.json

the registry:
https://studiorack.github.io/studiorack-registry/

and the site:
https://studiorack.github.io/studiorack-site/effects/studiorack/iem-plugin-suite/iem-plugin-suite

Thank-you!
